version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sihamed-web
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres-db:5432/sihamed2
      PORT: 3001
    ports:
      - '3001:3001'
    restart: unless-stopped

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sihamed2
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped

volumes:
  postgres-data:
